name: CI

on:
  push:
    branches: [develop]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Backend Tests
      run: |
        cd backend
        pip install -r requirements.txt
        pytest
    - name: Frontend Tests
      run: |
        cd frontend
        npm install
        npm run test
    - name: Build and Push Docker Images
      run: |
        docker build -t backend:latest backend
        docker build -t frontend:latest frontend

